locations/urls.py
from django.urls import include,path,re_path

from . import views


app_name = 'locations'
urlpatterns = [
	path('map/',views.map, name='map'),
	path('map_ll/',views.map_ll, name='map_ll'),
	path('map_ll_alpha/',views.map_ll_alpha, name='map_ll_alpha'),
	path('map_search/',views.map_search, name='map_search'),
	path('simple_map_search/',views.simple_map_search, 
        name='simple_map_search'),
	path('connection_view/',views.connection_view, name='connection_view'),
	path('connection_view/<str:text_identifier>/',
        views.connection_view, name='connection_view'),
	path('map_draw/',views.map_draw, name='map_draw'),
	path('ajax_instance/<str:app_name>/<str:model_name>/<int:pk>',
		views.ajax_instance, name='ajax_instance'),
	path('ajax_instances/<str:app_name>/<str:model_name>/<str:pks>',
		views.ajax_instances, name='ajax_instances'),
	path('ajax_popup/<str:markerid>/',views.ajax_popup, name='ajax_popup'),
	path('ajax_popup/<str:markerid>/<str:lat>/<str:lng>/',views.ajax_popup, 
		name='ajax_popup'),
	path('ajax_popup/<str:markerid>/<str:main_instance_markerid>/',
		views.ajax_popup,name='ajax_popup'),
	path('ajax_links/<str:markerid>/',views.ajax_links,name='ajax_links'),
	path('ajax_links/<str:markerid>/',views.ajax_links,name='ajax_links'),
	path('geojson_file/<str:filename>/',views.geojson_file, name='geojson_file'),
	path('geojson_file/geojson/<str:filename>/',views.geojson_file, 
		name='geojson_file'),
	path('map/<str:location_name>/',views.mapp, name='mapp'),
	path('delete/<int:pk>/<str:model_name>', views.delete, name='delete'),
	path('add_location/', views.edit_location, name='add_location'),
	path('add_location/<str:view>', views.edit_location, name='add_location'),
	path('edit_location/<int:pk>', views.edit_location, name='edit_location'),
	path('edit_location/<int:pk>/<str:focus>', views.edit_location, 
		name='edit_location'),
	path('style/', views.style_list, name='style_list'),
	path('add_style/', views.edit_style, name='add_style'),
	path('add_style/<str:view>', views.edit_style, name='add_style'),
	path('edit_style/<int:pk>', views.edit_style, name='edit_style'),
	path('edit_style/<int:pk>/<str:focus>', views.edit_style, name='edit_style'),
	path('figure/', views.figure_list, name='figure_list'),
	path('add_figure/', views.edit_figure, name='add_figure'),
	path('add_figure/<str:view>', views.edit_figure, name='add_figure'),
	path('edit_figure/<int:pk>', views.edit_figure, name='edit_figure'),
	path('edit_figure/<int:pk>/<str:focus>', views.edit_figure, name='edit_figure'),
	path('add_location_status/',views.add_location_status, 
		name='add_location_status'),
	path('add_location_status/<int:pk>',views.add_location_status, 
		name='add_location_status'),
	path('add_location_precision/',views.add_location_precision, 
		name='add_location_precision'),
	path('add_location_precision/<int:pk>',views.add_location_precision, 
		name='add_location_precision'),
	path('add_location_type/',views.add_location_type, name='add_location_type'),
	path('add_location_type/<int:pk>',views.add_location_type, 
		name='add_location_type'),
]

region/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import settings
from django.contrib.staticfiles.urls import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
	path('catalogue/',include('catalogue.urls')),
	path('locations/',include('locations.urls')),
	path('persons/',include('persons.urls')),
	path('utilities/',include('utilities.urls')),
	re_path(r'^select2/', include('django_select2.urls')),
	path('', include('catalogue.urls')),
	]

if settings.DEBUG:
	print('debug')
	urlpatterns += staticfiles_urlpatterns()
	urlpatterns += static(settings.MEDIA_URL, 
		document_root=settings.MEDIA_ROOT)
else:
	print('live')
	x = re_path(r'media/(?P<filename>.*)$', views.protected_media, 
		name='protected_media')
	urlpatterns.append(x)

utilities/urls.py
from django.urls import include,path,re_path

from . import views


app_name = 'utilities'
urlpatterns = [
	path('overview/',views.overview,name='overview'),
	path('close/',views.close,name='close'),
	path('list_view/<str:model_name>/<str:app_name>/',views.list_view,name='list_view'),
	path('list_view/<str:model_name>/<str:app_name>/<int:max_entries>',views.list_view,
		name='list_view'),
	path('timeline/',views.timeline,name='timeline'),
	path('add_comment/<str:app_name>/<str:model_name>/<int:entry_pk>/',views.edit_comment,
		name='add_comment'),
	path('add_comment/<int:user_pk>/',views.edit_comment,name='add_comment'),
	path('ajax_identifiers_to_instances/<str:identifiers>/',
		views.ajax_identifiers_to_instances, name='ajax_identifiers_to_instances'),
]

locations/views.py
from django.apps import apps
from django.core import serializers
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse
from django.forms import inlineformset_factory
from django.forms.models import model_to_dict
from .models import Location, LocationType, LocationRelation, Figure,Style 
from .forms import LocationForm, location_relation_formset, StyleForm,FigureForm
from .forms import LocationRelationForm, LocationTypeForm,LocationStatusForm
from .forms import LocationPrecisionForm
import json
import os
from utils.view_util import make_tabs,FormsetFactoryManager
from utils.map_util import gps2latlng, pop_up, get_all_location_ids_dict
from utils.model_util import instance2names
from utils import text_connection
from utils.search_view_helper import SearchView
from utils import query_hints
from utils.instance_links import Links
from utilities.views import getfocus, list_view, delete_model, edit_model
from utilities.views import add_simple_model
from utilities import search
from catalogue.models import Text,Illustration,Publication,Publisher,Periodical
from persons.models import Person, Movement
import time


def make_fname(name):
    o = name[0]
    for c in name[1:]:
        if c.isupper(): o+= '_' + c
        else: o += c
    return o.lower()


def create_simple_view(name):
    '''Create a simple view based on the Model name.
    Assumes the form only has a name field.
    '''
    c = 'def add_'+make_fname(name)+'(request,pk =None):\n'
    c += '\treturn add_simple_model(request,__name__,"'+name
    c +='","locations","add '+name+'",pk=pk)'
    return exec(c,globals())

#create simple forms for the following models 
names = 'LocationType,LocationPrecision,LocationStatus'
for name in names.split(','):
    create_simple_view(name)



def map_ll(request):
    '''current map view with new map implementation; 
    this new map view uses ajax/ lazy loading to speed up map rendering
    '''
    maplist = [x.plot() for x in get_querysets()]
    args = {'page_name':'map','maplist':maplist}
    return render(request,'locations/map_ll.html',args)


def map_ll_alpha(request):
    '''current map view with new map implementation; 
    this new map view uses ajax/ lazy loading to speed up map rendering
    '''
    d = get_all_location_ids_dict(add_names_gps = True)
    args = {'page_name':'map','d':d}
    return render(request,'locations/map_ll_alpha.html',args)

def map_search(request):
    s = SearchView(request)
    instances = s.search.filter()
    d = get_all_location_ids_dict(instances = instances, add_names_gps = True)
    s.var['page_name']='map search'
    s.var['d']=d
    return render(request, 'locations/map_search.html',s.var)

def simple_map_search(request):
    s = SearchView(request, restrict_to_texts = True)
    instances = s.search.filter()
    d = get_all_location_ids_dict(instances = instances, add_names_gps = True)
    query_terms = query_hints.get_queryterms()
    s.var['page_name']='map search'
    s.var['d']=d
    s.var['query_terms'] = query_terms
    return render(request, 'locations/simple_map_search.html',s.var)

def connection_view(request, text_identifier = None, pk = None):
    Text = apps.get_model('catalogue','Text')
    if text_identifier != None:
        try: pk = text_identifier.split('_')[2]
        except ValueError: print('no pk in text_identifier')
    if pk != None:
        instance = Text.objects.get(pk=pk)
    else: instance = Text.objects.get(pk = 1422)
    # else: raise ValueError('no pk or text_identifier')
    print(instance,'instance')
    f = serializers.serialize('json',[instance])
    print(f,'serial')
    connections = text_connection.text_connection(instance)
    print(connections)
    at = connections.all_texts
    d=get_all_location_ids_dict(instances=at,add_names_gps=True)
    print(d)
    var = {'instances':d,'connection_dict':connections.to_dict(),
        'instance':f}#model_to_dict(instance)}
    return render(request, 'locations/connection_view.html',var)


def map(request):
    '''old style map rendering, all data is prepared beforehand which 
    resulted in slow loading times
    '''
    # maplist = queryset2maplist(get_querysets())
    maplist = None
    args = {'page_name':'map','maplist':maplist}
    return render(request,'locations/map.html',args)

    


def edit_location(request, pk=None, focus = '', view='complete'):
    names='location_relation_formset'
    return edit_model(request, __name__,'Location','locations',pk,
        formset_names=names, 
        focus = focus, view=view)


def mapp(request, location_name = ''):
    if location_name == '': location_name = 'europe'
    map_name = location_name + '.js'
    var = {'map_name':map_name,'location_name':location_name}
    return render(request,'locations/map_location.html',var)


def germany(request):
    location_name = 'germany'
    map_name = location_name + '.js'
    var = {'map_name':map_name,'location_name':location_name}
    return render(request,'locations/markers.html',var)
    

def world(request):
    return render(request,'locations/world.html')

def delete(request, pk, model_name):
    return delete_model(request, __name__,model_name,'locations',pk)
# Create your views here.


def get_querysets(names = None):
    '''load all queryset based on model names in names.
    names can be list or comma seprated string 
    each item should follow this format: app_name$model_name
    '''
    if not names:
        names = 'Text,Illustration,Publication,Publisher,Periodical'.split(',')
        names = ['catalogue$'+name for name in names]
        names.extend('persons$Person,persons$Movement'.split(','))
    if type(names) == str: names = names.spilt(',')
    qs = []
    for name in names:
        app_name,model_name = name.split('$')
        model = apps.get_model(app_name,model_name)
        qs.extend(model.objects.all())
    return qs

def ajax_popup(request,markerid,main_instance_markerid = None):
    '''create a popup based on an async call with the relevant information
    '''
    print(markerid,main_instance_markerid,11111111111)
    app_name, model_name, pk,gps= markerid.split('_')
    latlng = gps2latlng(gps)
    model = apps.get_model(app_name,model_name)
    instance = model.objects.get(pk=pk)
    if main_instance_markerid:
        mi_an, mi_mn, mi_pk,mi_gps= main_instance_markerid.split('_')
        mi_model = apps.get_model(mi_an,mi_mn)
        mi_instance = mi_model.objects.get(pk=mi_pk)
        d = {'popup':instance.pop_up(mi_instance)}
    else:d = {'popup':instance.pop_up(latlng)}
    return JsonResponse(d)

def ajax_links(request,markerid):
    '''show links an instance has with other instance by plotting all on a map.
    '''
    app_name, model_name, pk,gps= markerid.split('_')
    model = apps.get_model(app_name,model_name)
    instance = model.objects.get(pk=pk)
    return JsonResponse({'links':Links(instance).plots})

def ajax_instance(request,app_name,model_name,pk):
    '''returns an instance base on app_name model_name and pk.'''
    model = apps.get_model(app_name,model_name)
    print(model,'model')
    instance = model.objects.get(pk=pk)
    print(instance,'instance')
    f = serializers.serialize('json',[instance])
    print(f,'serial')
    return JsonResponse({'instance':f})

def ajax_instances(request,app_name,model_name,pks):
    '''returns an instance base on app_name model_name and pk.'''
    start = time.time()
    model = apps.get_model(app_name,model_name)
    print('model',time.time() - start)
    print(model,'model')
    pks = pks.split(',')
    instances = model.objects.filter(pk__in = pks)
    print('instances',time.time() - start)
    print(instances,'instances')
    d = [x.sidebar_info for x in instances]
    print('info',time.time() - start)
    #d = serializers.serialize('json',instances)
    # print(d,'serial')
    return JsonResponse({'instances':d})
    

def geojson_file(request,filename):
    '''files used to draw a figure on a map.
    code for source of life map demo
    '''
    if not os.path.isfile('media/geojson/'+filename): data = {'file':False}
    a =  open('media/geojson/'+filename).read()
    try: data = json.loads(a)
    except: data = {'json':False}
    return JsonResponse(data)


def map_draw(request):
    '''view map demo source of life.
    '''
    f = Figure.objects.all()
    f = serializers.serialize('json',f)
    f = json.loads(f)
    s = Style.objects.all()
    s = serializers.serialize('json',s)
    s = json.loads(s)
    args = {'page_name':'map_draw','figures':f,'styles':s}
    return render(request,'locations/map_draw.html',args)

def edit_style(request, pk=None, focus = '', view='complete'):
    '''source of life map demo.
    '''
    return edit_model(request, __name__,'Style','locations',pk, 
        focus = focus, view=view)

def edit_figure(request, pk=None, focus = '', view='complete'):
    '''source of life map demo.
    '''
    return edit_model(request, __name__,'Figure','locations',pk, 
        focus = focus, view=view)

def style_list(request):
    '''source of life map demo
    '''
    return list_view(request, 'Style', 'locations')

def figure_list(request):
    '''source of life map demo
    '''
    return list_view(request, 'Figure', 'locations')
# Create your views here.

locations/templates/locations/add_figure.html
{% extends "utilities/base.html" %}

{% block head %}
	{{form.media.css}}
	<title>{{page_name}}</title>
{% endblock %}


{% block content %}
<form method="post" enctype="multipart/form-data" onsubmit="dosubmit();">
{% csrf_token %}

<div class="col-md-12 d-flex">
<h4 class="mt-2">{{page_name}}</h4>
{% if view != "inline" %}
	{% if page_name == "Edit figure"%}
	<a class ="btn btn-link ml-auto" href="{% url 'locations:add_figure' %}"
	role="button"><i class="fa fa-plus"></i></a>
	{% endif %}
	<a class ="btn btn-link ml-auto" href="{% url 'locations:figure_list' %}"
	role="button"><i class="fas fa-list"></i></a>
{% endif %}
</div>


{%if page_name == "Edit figure" and 'unknown' not in crud.last_update %}
	{% include 'utilities/change_log.html' %}
	{% else %} <p class="mb-4"></p>
{% endif %}
	<table class="table table-borderless table-sm">
	<tr class="d-flex">
		<td class="col-2">Name</th>
		<td class="col-9">{{form.name}} {{form.name.error}}</td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">Description</th>
		<td class="col-9">{{form.description}} {{form.description.error}}</td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">Style</th>
		<td class="col-9">{{form.style}} {{form.style.error}}</td>
		<td><a class = "btn btn-link btn-sm ml-auto" target = "_blank"
			href = "{% url 'locations:add_style' 'inline'%}"
			role="button"><i class="fa fa-plus"></i></a></td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">Start date</th>
		<td class="col-9">{{form.start_date}} {{form.start_date.error}}</td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">End date</th>
		<td class="col-9">{{form.end_date}} {{form.end_date.error}}</td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">File (geojson)</th>
		<td class="col-9">{{form.geojson}} {{form.geojson.error}}</td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">District number</th>
		<td class="col-9">{{form.district_number}} {{form.district_number.error}}</td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">City</th>
		<td class="col-9">{{form.city}} {{form.city.error}}</td>
	</tr>
	</table>


<input type="hidden" name="navbar" id="navbar" value="" />
<input type="hidden" name="navcontent" id="navcontent" value="" />
<input type="hidden" name="focus" id="focus" value="" />
<button type="submit" value="Submit" class ="btn btn-success">Save</button>
	{% if view == "inline" %}
		<a type="reset" value="Cancel" class ="btn btn-light"
		href="{% url 'utilities:close' %}">Cancel</a>
	{% else %}
		<button type="submit" name="save" value="add_another"
			 class ="btn btn-outline-success">Save | add another</button>
	{% endif %}
	{% if page_name == "Edit figure"%}
    <button type="submit" name="save" value="delete"
		 class ="btn btn-outline-danger">delete</button>
	{% endif %}
</form>

{{form.media.js}}
{% endblock %}

locations/templates/locations/add_location.html
{% extends "utilities/base.html" %}
{% load static %}
{% load getattribute %} 

{% block head %}
	{{form.media.css}}
	<title>{{page_name}}</title>
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
	integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
	crossorigin=""/>
     <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
       integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
   crossorigin=""></script>
	<style>
		#mapid {height: 200px;}
	</style>
{% endblock %}


{% block content %}
<form method="post" enctype="multipart/form-data" onsubmit="dosubmit();">
{% csrf_token %}

<div class="col-md-12 d-flex">
<h4 class="mt-2">{{page_name}}</h4>
{% if page_name == "Edit location" %}
    <p class="text-secondary small text-center pt-0 pb-0 mt-3 ml-5">{{instance.identifier}}</p></a>
{% endif %}
{% if view != "inline" %}
	{% if page_name == "Edit location"%}
	<a class ="btn btn-link ml-auto" href="{% url 'locations:add_location' %}"
	role="button"><i class="fa fa-plus"></i></a>
	{% endif %}
	<a class ="btn btn-link ml-auto" href="{% url 'utilities:list_view' 'Location' 'locations' 100 %}"
	role="button"><i class="fas fa-list"></i></a>
{% endif %}
</div>


{% include 'utilities/edit_minimize_tab.html' %}
<div class="tab-content">
    <div class="tab-pane fade" id="Edit">
	{%if page_name == "Edit location" and 'unknown' not in crud.last_update %}
		{% include 'utilities/change_log.html' %}
		{% else %} <p class="mb-4"></p>
	{% endif %}
<form method="post">
	<table class="table table-borderless table-sm" id="form_table">
	<tr class="d-flex">
		<td class="col-2">name</th>
		<td class="col-9">{{form.name}} {{form.name.error}}</td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">type</th>
		<td class="col-9">{{form.location_type}} {{form.location_type.error}}</td>
		{% if request.user|has_group:"typemaster" %}
		<td><a class = "btn btn-link btn-sm ml-auto" target = "_blank"
			href = "{% url 'locations:add_location_type' %}"
			role="button"><i class="fa fa-plus"></i></a></td>
		{% endif %}
	</tr>
	<tr class="d-flex">
		<td class="col-2">status</th>
		<td class="col-9">{{form.location_status}} {{form.location_status.error}}</td>
		{% if request.user|has_group:"typemaster" %}
		<td><a class = "btn btn-link btn-sm ml-auto" target = "_blank"
			href = "{% url 'locations:add_location_status' %}"
			role="button"><i class="fa fa-plus"></i></a></td>
		{% endif %}
	</tr>
	<tr class="d-flex">
		<td class="col-2">precision</th>
		<td class="col-9">{{form.location_precision}} {{form.location_precision.error}}</td>
		{% if request.user|has_group:"typemaster" %}
		<td><a class = "btn btn-link btn-sm ml-auto" target = "_blank"
			href = "{% url 'locations:add_location_precision' %}"
			role="button"><i class="fa fa-plus"></i></a></td>
		{% endif %}
	</tr>
	<tr class="d-flex">
		<td class="col-2">latitude</th>
		<td class="col-9">{{form.latitude}} {{form.latitude.error}}</td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">longitude</th>
		<td class="col-9">{{form.longitude}} {{form.longitude.error}}</td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">notes</th>
		<td class="col-9">{{form.notes}} {{form.notes.error}}</td>
	</tr>
	</table>

    </div>


    <div class="tab-pane fade" id="Minimize">
		<!-- you can minimize the text form -->
		<br>
        <h5 class="mb-1">{{form.instance.title}} </h5> 
		<br>
    </div>
</div>

{% if view == "inline" %}
{% else %}
{% include 'utilities/relation_tabs.html' %}

	<div class="tab-content">

		<div class="tab-pane fade" id="Contained by">
			{{location_relation_formset.management_form}}
			<table class="table table-borderless">
			<tr class ="d-flex">
			<th class="col-8">Location
				<a class = "btn btn-link btn-sm ml-auto" target = "_blank"
					href ="{% url 'locations:add_location' 'inline' %}" role="button">
					 <i class="fa fa-plus"></i></a>
				</th>
			<th><i class="fa fa-times text-danger"></i></th>
			</tr>
			{% for f in location_relation_formset.forms %}
				<tr class ="d-flex">
				<td class="col-8">{{f.container}} {{f.container.errors}}</td>
				<td class="col-1">{{f.DELETE}} {{f.id}}</td>
				</tr>
			{% endfor %}
			</table>
		</div>

	</div>

{% endif %}

{% if page_name == "Edit location"%}
    <hr>
    {{form.instance.latitude|json_script:'latitude'}}
    {{form.instance.longitude|json_script:'longitude'}}
    <div id="mapid" class="mt-0"></div>
    <br>
    <script src="{% static 'locations/add_location_map.js' %}">
    </script>
{% endif %}

<input type="hidden" name="navbar" id="navbar" value="" />
<input type="hidden" name="navcontent" id="navcontent" value="" />
<input type="hidden" name="focus" id="focus" value="" />
{% include 'utilities/save.html' %}

{% include 'utilities/tab_selector.html' %}
{% include 'utilities/helper.html' %}
{{form.media.js}}
{% endblock %}

locations/templates/locations/add_style.html
{% extends "utilities/base.html" %}

{% block head %}
	<title>{{page_name}}</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jscolor/2.3.3/jscolor.min.js"></script>

{% endblock %}


{% block content %}
<form method="post" enctype="multipart/form-data" onsubmit="dosubmit();">
{% csrf_token %}

<script>
// let's set defaults for all color pickers
jscolor.presets.default = {
    height: 181,              // make the picker box a little bigger
    position: 'right',        // position the picker to the right of the target
    previewPosition: 'right', // display color preview on the right side
    previewSize: 40,          // make color preview bigger
};
</script>


<div class="col-md-12 d-flex">
<h4 class="mt-2">{{page_name}}</h4>
{% if view != "inline" %}
	{% if page_name == "Edit style"%}
	<a class ="btn btn-link ml-auto" href="{% url 'locations:add_style' %}"
	role="button"><i class="fa fa-plus"></i></a>
	{% endif %}
	<a class ="btn btn-link ml-auto" href="{% url 'locations:style_list' %}"
	role="button"><i class="fas fa-list"></i></a>
{% endif %}
</div>


	{%if page_name == "Edit style" and 'unknown' not in crud.last_update %}
		{% include 'utilities/change_log.html' %}
		{% else %} <p class="mb-4"></p>
	{% endif %}
<form method="post">
	<table class="table table-borderless table-sm">
	<tr class="d-flex">
		<td class="col-2">name</th>
		<td class="col-6">{{form.name}} {{form.name.error}}</td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">color</th>
		<td class="col-6">{{form.color}} {{form.color.error}}</td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">stroke weight</th>
		<td class="col-6">{{form.stroke_weight}} {{form.stroke_weight.error}}</td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">stroke opacity</th>
		<td class="col-6">{{form.stroke_opacity}} {{form.stroke_opacity.error}}</td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">fill opacity</th>
		<td class="col-6">{{form.fill_opacity}} {{form.fill_opacity.error}}</td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">dashed</th>
		<td class="col-6">{{form.dashed}} {{form.dashed.error}}</td>
	</tr>
	<tr class="d-flex">
		<td class="col-2">z index</th>
		<td class="col-6">{{form.z_index}} {{form.z_index.error}}</td>
	</tr>
	</table>




<input type="hidden" name="navbar" id="navbar" value="" />
<input type="hidden" name="navcontent" id="navcontent" value="" />
<input type="hidden" name="focus" id="focus" value="" />
<button type="submit" value="Submit" class ="btn btn-success">Save</button>
	{% if view == "inline" %}
		<a type="reset" value="Cancel" class ="btn btn-light"
		href="{% url 'utilities:close' %}">Cancel</a>
	{% else %}
		<button type="submit" name="save" value="add_another"
			 class ="btn btn-outline-success">Save | add another</button>
	{% endif %}
	{% if page_name == "Edit style"%}
    <button type="submit" name="save" value="delete"
		 class ="btn btn-outline-danger">delete</button>
	{% endif %}
</form>
{{form.instance.fill_opacity}}

<script>

if(document.getElementById("id_fill_opacity").value == "") {
	document.getElementById("id_fill_opacity").value =0.3;
}
if(document.getElementById("id_stroke_opacity").value == "") {
	document.getElementById("id_stroke_opacity").value =0.8;
}
if(document.getElementById("id_stroke_weight").value == "") {
	document.getElementById("id_stroke_weight").value =3;
}
if(document.getElementById("id_z_index").value == "") {
	document.getElementById("id_z_index").value =0;
}
</script>

{% endblock %}