catalogue/urls.py
from django.urls import include,path,re_path

from . import views


app_name = 'catalogue'
urlpatterns = [
	path('',views.home,name='home'),
	path('acknowledgements/',views.acknowledgements,name='acknowledgements'),
	path('text/',views.text_list,name='text_view'),
	path('ajax_test/',views.ajax_test,name='ajax_test'),
	path('add_illustration/', views.edit_illustration, name='add_illustration'),
	path('add_text/', views.edit_text, name='add_text'),
	path('add_periodical/', views.edit_periodical, name='add_periodical'),
	path('add_publication/', views.edit_publication, name='add_publication'),
	path('add_publisher/', views.edit_publisher, name='add_publisher'),
	path('add_illustration/<str:view>', views.edit_illustration, 
		name='add_illustration'),
	path('add_text/<str:view>', views.edit_text, name='add_text'),
	path('add_periodical/<str:view>', views.edit_periodical, name='add_periodical'),
	path('add_publication/<str:view>', views.edit_publication, 
		name='add_publication'),
	path('add_publisher/<str:view>', views.edit_publisher, name='add_publisher'),
	path('edit_text/<int:pk>', views.edit_text, name='edit_text'),
	path('edit_text/<int:pk>/<str:focus>', views.edit_text, name='edit_text'),
	path('edit_periodical/<int:pk>', views.edit_periodical, name='edit_periodical'),
	path('edit_periodical/<int:pk>/<str:focus>', views.edit_periodical, 
		name='edit_periodical'),
	path('edit_publication/<int:pk>', views.edit_publication, name='edit_publication'),
	path('edit_publication/<int:pk>/<str:focus>', views.edit_publication, 
		name='edit_publication'),
	path('edit_publisher/<int:pk>', views.edit_publisher, name='edit_publisher'),
	path('edit_publisher/<int:pk>/<str:focus>', views.edit_publisher, 
		name='edit_publisher'),
	path('edit_illustration/<int:pk>', views.edit_illustration, 
		name='edit_illustration'),
	path('edit_illustration/<int:pk>/<str:focus>', 
		views.edit_illustration, name='edit_illustration'),
	path('delete/<int:pk>/<str:model_name>', views.delete, name='delete'),
	path('d_illustration/<int:pk>',views.detail_illustration,
		name='detail_illustration'),
	path('d_publication/<int:pk>',views.detail_publication,
		name='detail_publication'),
	path('detail_publication/<int:pk>',views.detail_publication,
		name='detail_publication'),
	path('d_periodical/<int:pk>',views.detail_periodical,
		name='detail_periodical'),
	path('d_text/<int:pk>',views.detail_text,
		name='detail_text'),
	path('detail_text/<int:pk>',views.detail_text,
		name='detail_text'),
	path('d_publisher/<int:pk>',views.detail_publisher,
		name='detail_publisher'),
]



def create_simple_path(name):
	'''creates a simple view based on the model name
	Assumes the form only has a name field.
	'''
	n = views.make_fname(name)
	o = []
	p = "path('add_"+n+"/', views.add_"+n+" , name='add_"+n+"')"
	o.append(eval(p))
	p = "path('add_"+n+"/<int:pk>', views.add_"+n+" , name='add_"+n+"')"
	o.append(eval(p))
	return o

names = 'Genre,TextType,CopyRight,IllustrationCategory,PublicationType'
names += ',TextTextRelationType,IllustrationIllustrationRelationType'
names += ',IllustrationType'
for name in names.split(','):
	urlpatterns.extend(create_simple_path(name))

locations/urls.py
from django.urls import include,path,re_path

from . import views


app_name = 'locations'
urlpatterns = [
	path('map/',views.map, name='map'),
	path('map_ll/',views.map_ll, name='map_ll'),
	path('map_ll_alpha/',views.map_ll_alpha, name='map_ll_alpha'),
	path('map_search/',views.map_search, name='map_search'),
	path('simple_map_search/',views.simple_map_search, 
        name='simple_map_search'),
	path('connection_view/',views.connection_view, name='connection_view'),
	path('connection_view/<str:text_identifier>/',
        views.connection_view, name='connection_view'),
	path('map_draw/',views.map_draw, name='map_draw'),
	path('ajax_instance/<str:app_name>/<str:model_name>/<int:pk>',
		views.ajax_instance, name='ajax_instance'),
	path('ajax_instances/<str:app_name>/<str:model_name>/<str:pks>',
		views.ajax_instances, name='ajax_instances'),
	path('ajax_popup/<str:markerid>/',views.ajax_popup, name='ajax_popup'),
	path('ajax_popup/<str:markerid>/<str:lat>/<str:lng>/',views.ajax_popup, 
		name='ajax_popup'),
	path('ajax_popup/<str:markerid>/<str:main_instance_markerid>/',
		views.ajax_popup,name='ajax_popup'),
	path('ajax_links/<str:markerid>/',views.ajax_links,name='ajax_links'),
	path('ajax_links/<str:markerid>/',views.ajax_links,name='ajax_links'),
	path('geojson_file/<str:filename>/',views.geojson_file, name='geojson_file'),
	path('geojson_file/geojson/<str:filename>/',views.geojson_file, 
		name='geojson_file'),
	path('map/<str:location_name>/',views.mapp, name='mapp'),
	path('delete/<int:pk>/<str:model_name>', views.delete, name='delete'),
	path('add_location/', views.edit_location, name='add_location'),
	path('add_location/<str:view>', views.edit_location, name='add_location'),
	path('edit_location/<int:pk>', views.edit_location, name='edit_location'),
	path('edit_location/<int:pk>/<str:focus>', views.edit_location, 
		name='edit_location'),
	path('style/', views.style_list, name='style_list'),
	path('add_style/', views.edit_style, name='add_style'),
	path('add_style/<str:view>', views.edit_style, name='add_style'),
	path('edit_style/<int:pk>', views.edit_style, name='edit_style'),
	path('edit_style/<int:pk>/<str:focus>', views.edit_style, name='edit_style'),
	path('figure/', views.figure_list, name='figure_list'),
	path('add_figure/', views.edit_figure, name='add_figure'),
	path('add_figure/<str:view>', views.edit_figure, name='add_figure'),
	path('edit_figure/<int:pk>', views.edit_figure, name='edit_figure'),
	path('edit_figure/<int:pk>/<str:focus>', views.edit_figure, name='edit_figure'),
	path('add_location_status/',views.add_location_status, 
		name='add_location_status'),
	path('add_location_status/<int:pk>',views.add_location_status, 
		name='add_location_status'),
	path('add_location_precision/',views.add_location_precision, 
		name='add_location_precision'),
	path('add_location_precision/<int:pk>',views.add_location_precision, 
		name='add_location_precision'),
	path('add_location_type/',views.add_location_type, name='add_location_type'),
	path('add_location_type/<int:pk>',views.add_location_type, 
		name='add_location_type'),
]

persons/urls.py
from django.urls import include,path,re_path

from . import views


app_name = 'persons'
urlpatterns = [
	path('add_person/', views.edit_person, name='add_person'),
	path('add_person/<str:view>', views.edit_person, name='add_person'),
	path('add_movement/', views.edit_movement, name='add_movement'),
	path('add_movement/<str:view>', views.edit_movement, 
		name='add_movement'),
	path('edit_person/<int:pk>', views.edit_person, name='edit_person'),
	path('edit_person/<int:pk>/<str:focus>', 
		views.edit_person, name='edit_person'),
	path('edit_movement/<int:pk>', views.edit_movement, 
		name='edit_movement'),
	path('edit_movement/<int:pk>/<str:focus>', views.edit_movement, 
		name='edit_movement'),
	path('person/add_pseudonym',views.add_pseudonym,
		name='add_pseudonym'),
	path('delete/<int:pk>/<str:model_name>', views.delete, name='delete'),
	path('d_movement/<int:pk>',views.detail_movement,
		name='detail_movement'),
	path('d_person/<int:pk>',views.detail_person,
		name='detail_person'),
	path('detail_person/<int:pk>',views.detail_person,
		name='detail_person'),
]

def create_simple_path(name):
	'''creates a simple view based on the model name
	Assumes the form only has a name field.
	'''
	n = views.make_fname(name)
	o = []
	p = "path('add_"+n+"/', views.add_"+n+" , name='add_"+n+"')"
	o.append(eval(p))
	p = "path('add_"+n+"/<int:pk>', views.add_"+n+" , name='add_"+n+"')"
	o.append(eval(p))
	return o

names = 'PersonPersonRelationType,PersonLocationRelationType,PersonTextRelationRole'
names += ',PersonIllustrationRelationRole,PersonMovementRelationRole'
names += ',PersonPeriodicalRelationRole,MovementType,Pseudonym'
for name in names.split(','):
	urlpatterns.extend(create_simple_path(name))

'''
temp = [
	path('person/add_person_text_relation_role',views.add_person_text_relation_role,
		name='add_person_text_relation_role'),
	path('person/add_person_illustration_relation_role',
		views.add_person_illustration_relation_role,
		name='add_person_illustration_relation_role'),
	path('person/add_person_location_relation',views.add_person_location_relation,
		name='add_person_location_relation'),
	path('person/add_person_movement_relation_role',
		views.add_person_movement_relation_role,
		name='add_person_movement_relation_role'),
	path('person/add_person_periodical_relation_role',
		views.add_person_periodical_relation_role,
		name='add_person_periodical_relation_role'),
	path('person/add_movement_type', views.add_movement_type,name='add_movement_type'),
	path('person/add_person_person_relation_type', views.add_person_person_relation_type,
		name='add_person_person_relation_type'),
]
'''

region/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import settings
from django.contrib.staticfiles.urls import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
	path('catalogue/',include('catalogue.urls')),
	path('locations/',include('locations.urls')),
	path('persons/',include('persons.urls')),
	path('utilities/',include('utilities.urls')),
	re_path(r'^select2/', include('django_select2.urls')),
	path('', include('catalogue.urls')),
	]

if settings.DEBUG:
	print('debug')
	urlpatterns += staticfiles_urlpatterns()
	urlpatterns += static(settings.MEDIA_URL, 
		document_root=settings.MEDIA_ROOT)
else:
	print('live')
	x = re_path(r'media/(?P<filename>.*)$', views.protected_media, 
		name='protected_media')
	urlpatterns.append(x)

utilities/urls.py
from django.urls import include,path,re_path

from . import views


app_name = 'utilities'
urlpatterns = [
	path('overview/',views.overview,name='overview'),
	path('close/',views.close,name='close'),
	path('list_view/<str:model_name>/<str:app_name>/',views.list_view,name='list_view'),
	path('list_view/<str:model_name>/<str:app_name>/<int:max_entries>',views.list_view,
		name='list_view'),
	path('timeline/',views.timeline,name='timeline'),
	path('add_comment/<str:app_name>/<str:model_name>/<int:entry_pk>/',views.edit_comment,
		name='add_comment'),
	path('add_comment/<int:user_pk>/',views.edit_comment,name='add_comment'),
	path('ajax_identifiers_to_instances/<str:identifiers>/',
		views.ajax_identifiers_to_instances, name='ajax_identifiers_to_instances'),
]

utilities/models.py
from django.apps import apps
from django.db import models
from django.utils import timezone
from utils.model_util import id_generator, info, instance2names
from utils.map_util import pop_up, get_location_name,gps2latlng
from django.contrib.auth import get_user_model

User = get_user_model()
dargs = {'on_delete':models.SET_NULL,'blank':True,'null':True}

class Queryterm(models.Model):
    term = models.CharField(max_length=1000,unique=True)

class RelationModel(models.Model):
    '''abstract model for relational models, e.g. text person relation model
        provide other function: gives field name of the other field name
        e.g. in previous example if person is provided text would be returned
    '''
    model_fields = ['','']
    other = False
    other_field_name = False
    relation_field = ''

    class Meta:
        abstract=True

    def set_other(self,main_instance):
        '''a relation model connects two models e.g. text & person
        if main_instance is of type text the other instance will be of type person
        and stored on attribute .other
        '''
        for field_name in self.model_fields:
            instance = getattr(self,field_name)
            if instance == main_instance: continue
            else: 
                self.other = instance
                self.other_field_name =field_name

    def plot(self):
        app_name, model_name = instance2names(self) 
        oan,omn = instance2names(self.other)
        gps = str(self.other.gps.split(' | ')).replace("'",'')
        d = {'app_name':app_name, 'model_name':model_name, 
            'gps':gps, 'pk':self.pk,'layer_name':omn}
        return d

    def pop_up(self,main_instance):
        self.set_other(main_instance)
        if not self.other: return 'could not construct relation'
        latlng = gps2latlng(self.other.gps)
        m = self.other.pop_up(latlng)
        return m

    def get_other(self, instance):
        for field_name in self.model_fields:
            other_instance = getattr(self,field_name)
            if instance == other_instance: continue
            return other_instance


class SimpleModel(models.Model):
    '''abstract model for simple model with only a name, notes and description.'''
    name = models.CharField(max_length=300,default='',unique=True)
    description = models.TextField(blank=True,null=True)
    notes= models.TextField(blank=True,null=True)
    endnode = True

    def __str__(self): 
        return self.name
                     
    class Meta:        
        abstract=True 

class generic(models.Model):
    '''used for setting persmission'''
    pass


class Language(models.Model, info):
    name = models.CharField(max_length=100, unique = True)
    iso = models.CharField(max_length=3,null=True,blank=True)
    endnode = True

    def __str__(self):
        return self.name
# Create your models here.

class GroupTag(models.Model,info):
    '''can be added to an instance to group instances together.
    this could be used to process a set of instances
    '''
    name = models.CharField(max_length=300)
    created = models.DateTimeField(auto_now_add=True,null=True)
    modified = models.DateTimeField(auto_now_add=False,null=True,blank=True)
    done = models.BooleanField(default=False)
    tag_type = models.CharField(max_length=300,blank=True, null =True)
    index = models.PositiveIntegerField(null=True,blank=True) 
    description = models.TextField(blank=True,null=True)

    def save(self, *args, **kwargs):  
        if not self.id:
            self.created = timezone.now()
        else: self.modified = timezone.now()
        return super(GroupTag, self).save(*args,**kwargs)

    def __lt__(self,other):
        return self.created < other.created

    def __repr__(self):
        m = self.name + ' ' + str(self.created).split('.')[0]
        if self.index != None:m += ' ' + str(self.index)
        return m


class Comment(models.Model,info):
    app_name = models.CharField(max_length=100,default ='')
    model_name = models.CharField(max_length=100,default = '')
    entry_pk = models.PositiveIntegerField(null=True,blank=True)
    fixed = models.BooleanField(default=False)
    subject= models.CharField(max_length=300)
    description = models.TextField(blank=True,null=True)
    user_commentator= models.CharField(max_length=1000, default= '')
    user_addressee= models.CharField(max_length=1000, default='')
    comment= models.TextField(blank=True)


    def __str__(self):
        m = self.app_name + ' ' + self.model_name + ' ' + self.subject
        return m

    def __lt__(self,other):
        return self.created < other.created

    def _add_crud(self):
        if not hasattr(self,'crud'):
            from utils.view_util import Crud
            self.crud = Crud(self)
            
    @property
    def created_time(self):
        self._add_crud()
        return self.crud.created_time

    @property
    def created_by(self):
        self._add_crud()
        return self.crud.created_by

    @property
    def updated_time(self):
        self._add_crud()
        return self.crud.last_update_time

    @property
    def updated_by(self):
        self._add_crud()
        return self.crud.last_update_by

    @property
    def about(self):
        try:return apps.get_model(self.app_name,self.model_name).objects.get(pk = self.entry_pk)
        except: return ''

    @property
    def edit_url(self):
        return self.app_name + ':edit_' + self.model_name 
        

class Modelname(models.Model,info):
    model_name = models.CharField(max_length=100,default = '')
    app_name = models.CharField(max_length=100,default = '')


    def __repr__(self):
        return self.model_name

persons/templates/persons/add_movement.html
{% extends "utilities/base.html" %}
{% load getattribute %} 

{% block head %}
	{{form.media.css}}
{% endblock %}

{% block content %}
<div class="col-md-12 d-flex">
	<h4 class="mt-2">{{page_name}}</h4> 
    {% if page_name == "Edit movement" %}
        <p class="text-secondary small text-center pt-0 pb-0 mt-3 ml-5">{{instance.identifier}}</p></a>
    {% endif %}
	{% if page_name == "Edit movement"%}
		<a class ="btn btn-link ml-auto" href="{% url 'persons:add_movement' %}"
			role="button"><i class="fa fa-plus"></i></a>
			{% include 'utilities/detail_view_link.html' %}
	{% endif %}
	<a class ="btn btn-link ml-auto" 
		href="{% url 'utilities:list_view' 'Movement' 'persons'%}" 
		role="button">
			<i class="fas fa-list"></i>
	</a>
	{% if instance.pk %}
		<a class ="btn btn-link ml-auto" 
			href="{% url 'utilities:add_comment' app_name model_name instance.pk %}"
			role="button" target="_blank">
				<i class="far fa-comments"></i>
	</a>
	{% endif %}
</div>


<!-- dosubmit function can be found in template/utilities/tab_selector.html -->
<form name="myform" id="myform" method = "post" onsubmit="dosubmit();">
{% csrf_token %}

{% include 'utilities/edit_minimize_tab.html' %}

<div class="tab-content">

    <div class="tab-pane fade" id="Edit">
		<!-- person form is defined in a seperate template -->
		{% if page_name == "Edit movement" and 'unknown' not in crud.last_update %}
			{% include 'utilities/change_log.html' %}
			{% else %} <p class="mb-4"></p>
		{% endif %}

		<table class="table table-borderless" id="form_table">
			<tr class="d-flex">
				<th class="col-2">Name</th>
				<td class="col-8">{{form.name}}</td>
			</tr>
			<tr class="d-flex">
				<th class="col-2">Type</th>
				<td class="col-8">{{form.movement_type}}</td>
				<td><a class = "btn btn-link btn-sm ml-auto" target = "_blank"
						href ="{% url 'persons:add_movement_type'%}"
						role="button"><i class="fa fa-plus"></i></a>
				</td>
			</tr>
			<tr class="d-flex">
				<th class="col-2">Location</th>
				<td class="col-8">{{form.location}}</td>
				<td><a class = "btn btn-link btn-sm ml-auto" target = "_blank"
						href ="{% url 'locations:add_location' 'inline' %}" 
						role="button"><i class="fa fa-plus"></i></a>
				</td>
			</tr>
			<tr class="d-flex">
				<th class="col-2">Founded</th>
				<td class="col-8">{{form.founded}}</td>
			</tr>
			<tr class="d-flex">
				<th class="col-2">Closure</th>
				<td class="col-8">{{form.closure}}</td>
			</tr>
			<tr class="d-flex">
				<th class="col-2">Notes</th>
				<td class="col-8">{{form.notes}}</td>
			</tr>
		</table>

    </div>

    <div class="tab-pane fade" id="Minimize">
		<!-- you can minimize the person form -->
		<br>
        <h5>{{form.instance.name}}</h5>
    </div>

</div>
<hr>


{% if view == "inline" %}
{% else %}

<!-- Inline formsets to linking persons to other items -->
{% include 'utilities/relation_tabs.html' %}

<div class="tab-content">
    <div class="tab-pane fade" id="Persons">

	{{movementperson_formset.management_form}}
	<table class="table table-borderless">
		<tr class ="d-flex">
			<th class="col-4">Person
				<a class = "btn btn-link btn-sm ml-auto" target = "_blank"
					href ="{% url 'persons:add_person' 'inline'%}" role="button">
					<i class="fa fa-plus"></i></a>
				</th>
			<th class="col-4">Role
				{% if request.user|has_group:"typemaster" %}
					<a class = "btn btn-link btn-sm ml-auto" target = "_blank"
						href ="{% url 'persons:add_person_movement_relation_role' %}" 
						role="button">
						<i class="fa fa-plus"></i></a>
				{% endif %}
				</th>
			<th><i class="fa fa-times text-danger"></i></th>
		</tr>
		{% for f in movementperson_formset.forms %}
			<tr class ="d-flex">
				<td class="col-4">{{f.person}} {{f.person.errors}}</td>
				<td class="col-4">{{f.role}} {{f.role.errors}}</td>
				<td class="col-1">{{f.DELETE}} {{f.id}}</td>
			</tr>
		{% endfor %}
	</table>
	</div>

</div>
<hr> 

{% endif %}

<!-- current tab state is stored here to maintain it after submit,see tab_selector  -->
<input type="hidden" name="navbar" id="navbar" value="" />
<input type="hidden" name="navcontent" id="navcontent" value="" />
<input type="hidden" name="focus" id="focus" value="" />

{% include 'utilities/save.html' %}


{% include 'utilities/helper.html' %}
{{form.media.js}}

{% include 'utilities/tab_selector.html' %}

{% endblock content %}

{% block right %}
{% include 'utilities/complete_approved.html' %}
{% endblock %}

persons/templates/persons/literary_movement_list.html
<!-- test view to print data in a table from model --> 
{% extends "utilities/base.html" %}
{% if literary_movement_list %}

{% block content %}

<div class="d-flex">

<table class="table table-hover">
	<tr> 
	<th>Name</th>
	<th>Location</th>
	</tr>
	{% for movement in literary_movement_list %}
	<tr onclick='window.location="{% url 'persons:edit_literary_movement' movement.pk %}"'>
		<td>{{movement.name}}</td>
		<td>{{movement.location_string}}</td>
	</tr>
	{% endfor %}
</table>

<a class ="btn btn-link ml-auto" href="{% url 'persons:add_literary_movement' %}" role="button">Add literary movement</a>
</div>

{% endblock content %}

{% else %}
	<p>no persons are available</p>
{% endif %}

<!-- minimal style to make the table more readable -->
<!-- <style> -->
<!-- table { -->
<!-- 	border-spacing: 20px 0; -->
<!-- } -->
<!-- th { -->
<!-- 	color: blue; -->
<!-- } -->
<!-- </style> -->
<!-- test -->

persons/templates/persons/movement_list.html
<!-- test view to print data in a table from model --> 
{% extends "utilities/base.html" %}
{% if movement_list %}

{% block content %}

{% include 'utilities/list_search_bar.html' %}

<div class="d-flex">

<table class="table">
	<tr> 
	<th><a href="?order_by=name,{{order}},{{direction}},{{query}}" 
		style="text-decoration:none;">Name</a></th>
	<th><a href="?order_by=location,{{order}},{{direction}},{{query}}" 
		style="text-decoration:none;">Location</a></th>
	<th><a href="?order_by=connection_count,{{order}},{{direction}},{{query}}" 
		style="text-decoration:none;">#con.</a></th>
	<th></th>
	</tr>
	{% for movement in movement_list %}
    {% if not perms.utilities.add_generic %}
	{% elif movement.approved %}
	<tr style="background:#c0edc0;">
	{% elif movement.complete %}
	<tr style="background:#fff494;">
	{% elif movement.incomplete %}
	<tr style="background:#ffb694;">
	{% endif %}
		<td>{{movement.name}}</td>
		<td>{{movement.location_str}}</td>
		<td>{{movement.connection_count}}</td>
		<td style="white-space:nowrap;">
    {% if perms.utilities.delete_generic %}
			<a class = "btn btn-link btn-sm ml-auto"
				href ="{% url 'persons:delete' movement.pk 'Movement' %}"
				role="button">
					<i class="fa fa-trash text-secondary"></i>
			</a>
    {% endif %}
    {% if perms.utilities.add_generic %}
			<a class = "btn btn-link btn-sm ml-auto"
				href ="{% url 'persons:edit_movement' movement.pk %}"
				role="button">
					<i class="far fa-edit text-secondary"></i>
			</a>
    {% endif %}
			<a class="btn btn-link btn-sm ml-auto" 
				href="{% url movement.detail_url movement.pk %}"
				role="button">
				   <i class="fas fa-eye text-secondary"></i>
			</a>
		</td>
	</tr>
	{% endfor %}
</table>

</div>

{% endblock content %}

{% else %}
	<p>no movements are available</p>
{% endif %}

<!-- minimal style to make the table more readable -->
<!-- <style> -->
<!-- table { -->
<!-- 	border-spacing: 20px 0; -->
<!-- } -->
<!-- th { -->
<!-- 	color: blue; -->
<!-- } -->
<!-- </style> -->
<!-- test -->

persons/templates/persons/person_list.html
<!-- test view to print data in a table from model --> 
{% extends "utilities/base.html" %}
{% if person_list %}

{% block content %}
{% include 'utilities/list_search_bar.html' %}

<div class="d-flex">

<table class="table">
	<tr> 
	<th><a href="?order_by=first_name,{{order}},{{direction}},{{query}}" 
		style="text-decoration:none;">First name</a></th>
	<th><a href="?order_by=last_name,{{order}},{{direction}},{{query}}" 
		style="text-decoration:none;">Last name</a></th>
	<th><a href="?order_by=sex,{{order}},{{direction}},{{query}}" 
		style="text-decoration:none;">Sex</a></th>
	<th><a href="?order_by=birth_year,{{order}},{{direction}},{{query}}" 
		style="text-decoration:none;">Born</a></th>
	<th><a href="?order_by=death_year,{{order}},{{direction}},{{query}}" 
		style="text-decoration:none;">Died</a></th>
	<th><a href="?order_by=birth_place,{{order}},{{direction}},{{query}}" 
		style="text-decoration:none;">Birth place</a></th>
	<th><a href="?order_by=connection_count,{{order}},{{direction}},{{query}}" 
		style="text-decoration:none;">#con.</a></th>
	<th></th>
	<!-- create header -->
	</tr>
	{% for person in person_list %}
    {% if not perms.utilities.add_generic %}
	{% elif person.approved %}
	<tr style="background:#c0edc0;">
	{% elif person.complete %}
	<tr style="background:#fff494;">
	{% elif person.incomplete %}
	<tr style="background:#ffb694;">
	{% endif %}
		<td>{{person.first_name|default:''}}</td>
		<td>{{person.last_name|default:''}}</td>
		<td>{{person.gender|default:''}}</td>
		<td>{{person.birth_year|default:''}}</td>
		<td>{{person.death_year|default:''}}</td>
		<td>{{person.birth_place|default:''}}</td>
		<td>{{person.connection_count}}</td>
		<td style="white-space:nowrap;">
    {% if perms.utilities.delete_generic %}
			<a class = "btn btn-link btn-sm ml-auto"
				href ="{% url 'persons:delete' person.pk 'Person' %}"
				role="button">
					<i class="fa fa-trash text-secondary"></i>
			</a>
    {% endif %}
    {% if perms.utilities.add_generic %}
			<a class = "btn btn-link btn-sm ml-auto"
				href ="{% url 'persons:edit_person' person.pk %}"
				role="button">
					<i class="far fa-edit text-secondary"></i>
			</a>
    {% endif %}
			<a class="btn btn-link btn-sm ml-auto" 
				href="{% url person.detail_url person.pk %}"
				role="button">
				   <i class="fas fa-eye text-secondary"></i>
			</a>
		</td>
	</tr>
	{% endfor %}
</table>
</div>

{% endblock content %}

{% else %}
	<p>no persons are available</p>
{% endif %}

<!-- minimal style to make the table more readable -->
<!-- <style> -->
<!-- table { -->
<!-- 	border-spacing: 20px 0; -->
<!-- } -->
<!-- th { -->
<!-- 	color: blue; -->
<!-- } -->
<!-- </style> -->
<!-- test -->