locations/urls.py
from django.urls import include,path,re_path

from . import views


app_name = 'locations'
urlpatterns = [
	path('map/',views.map, name='map'),
	path('map_ll/',views.map_ll, name='map_ll'),
	path('map_ll_alpha/',views.map_ll_alpha, name='map_ll_alpha'),
	path('map_search/',views.map_search, name='map_search'),
	path('simple_map_search/',views.simple_map_search, 
        name='simple_map_search'),
	path('connection_view/',views.connection_view, name='connection_view'),
	path('connection_view/<str:text_identifier>/',
        views.connection_view, name='connection_view'),
	path('map_draw/',views.map_draw, name='map_draw'),
	path('ajax_instance/<str:app_name>/<str:model_name>/<int:pk>',
		views.ajax_instance, name='ajax_instance'),
	path('ajax_instances/<str:app_name>/<str:model_name>/<str:pks>',
		views.ajax_instances, name='ajax_instances'),
	path('ajax_popup/<str:markerid>/',views.ajax_popup, name='ajax_popup'),
	path('ajax_popup/<str:markerid>/<str:lat>/<str:lng>/',views.ajax_popup, 
		name='ajax_popup'),
	path('ajax_popup/<str:markerid>/<str:main_instance_markerid>/',
		views.ajax_popup,name='ajax_popup'),
	path('ajax_links/<str:markerid>/',views.ajax_links,name='ajax_links'),
	path('ajax_links/<str:markerid>/',views.ajax_links,name='ajax_links'),
	path('geojson_file/<str:filename>/',views.geojson_file, name='geojson_file'),
	path('geojson_file/geojson/<str:filename>/',views.geojson_file, 
		name='geojson_file'),
	path('map/<str:location_name>/',views.mapp, name='mapp'),
	path('delete/<int:pk>/<str:model_name>', views.delete, name='delete'),
	path('add_location/', views.edit_location, name='add_location'),
	path('add_location/<str:view>', views.edit_location, name='add_location'),
	path('edit_location/<int:pk>', views.edit_location, name='edit_location'),
	path('edit_location/<int:pk>/<str:focus>', views.edit_location, 
		name='edit_location'),
	path('style/', views.style_list, name='style_list'),
	path('add_style/', views.edit_style, name='add_style'),
	path('add_style/<str:view>', views.edit_style, name='add_style'),
	path('edit_style/<int:pk>', views.edit_style, name='edit_style'),
	path('edit_style/<int:pk>/<str:focus>', views.edit_style, name='edit_style'),
	path('figure/', views.figure_list, name='figure_list'),
	path('add_figure/', views.edit_figure, name='add_figure'),
	path('add_figure/<str:view>', views.edit_figure, name='add_figure'),
	path('edit_figure/<int:pk>', views.edit_figure, name='edit_figure'),
	path('edit_figure/<int:pk>/<str:focus>', views.edit_figure, name='edit_figure'),
	path('add_location_status/',views.add_location_status, 
		name='add_location_status'),
	path('add_location_status/<int:pk>',views.add_location_status, 
		name='add_location_status'),
	path('add_location_precision/',views.add_location_precision, 
		name='add_location_precision'),
	path('add_location_precision/<int:pk>',views.add_location_precision, 
		name='add_location_precision'),
	path('add_location_type/',views.add_location_type, name='add_location_type'),
	path('add_location_type/<int:pk>',views.add_location_type, 
		name='add_location_type'),
]

region/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import settings
from django.contrib.staticfiles.urls import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
	path('catalogue/',include('catalogue.urls')),
	path('locations/',include('locations.urls')),
	path('persons/',include('persons.urls')),
	path('utilities/',include('utilities.urls')),
	re_path(r'^select2/', include('django_select2.urls')),
	path('', include('catalogue.urls')),
	]

if settings.DEBUG:
	print('debug')
	urlpatterns += staticfiles_urlpatterns()
	urlpatterns += static(settings.MEDIA_URL, 
		document_root=settings.MEDIA_ROOT)
else:
	print('live')
	x = re_path(r'media/(?P<filename>.*)$', views.protected_media, 
		name='protected_media')
	urlpatterns.append(x)

utilities/urls.py
from django.urls import include,path,re_path

from . import views


app_name = 'utilities'
urlpatterns = [
	path('overview/',views.overview,name='overview'),
	path('close/',views.close,name='close'),
	path('list_view/<str:model_name>/<str:app_name>/',views.list_view,name='list_view'),
	path('list_view/<str:model_name>/<str:app_name>/<int:max_entries>',views.list_view,
		name='list_view'),
	path('timeline/',views.timeline,name='timeline'),
	path('add_comment/<str:app_name>/<str:model_name>/<int:entry_pk>/',views.edit_comment,
		name='add_comment'),
	path('add_comment/<int:user_pk>/',views.edit_comment,name='add_comment'),
	path('ajax_identifiers_to_instances/<str:identifiers>/',
		views.ajax_identifiers_to_instances, name='ajax_identifiers_to_instances'),
]

locations/views.py
from django.apps import apps
from django.core import serializers
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse
from django.forms import inlineformset_factory
from django.forms.models import model_to_dict
from .models import Location, LocationType, LocationRelation, Figure,Style 
from .forms import LocationForm, location_relation_formset, StyleForm,FigureForm
from .forms import LocationRelationForm, LocationTypeForm,LocationStatusForm
from .forms import LocationPrecisionForm
import json
import os
from utils.view_util import make_tabs,FormsetFactoryManager
from utils.map_util import gps2latlng, pop_up, get_all_location_ids_dict
from utils.model_util import instance2names
from utils import text_connection
from utils.search_view_helper import SearchView
from utils import query_hints
from utils.instance_links import Links
from utilities.views import getfocus, list_view, delete_model, edit_model
from utilities.views import add_simple_model
from utilities import search
from catalogue.models import Text,Illustration,Publication,Publisher,Periodical
from persons.models import Person, Movement
import time


def make_fname(name):
    o = name[0]
    for c in name[1:]:
        if c.isupper(): o+= '_' + c
        else: o += c
    return o.lower()


def create_simple_view(name):
    '''Create a simple view based on the Model name.
    Assumes the form only has a name field.
    '''
    c = 'def add_'+make_fname(name)+'(request,pk =None):\n'
    c += '\treturn add_simple_model(request,__name__,"'+name
    c +='","locations","add '+name+'",pk=pk)'
    return exec(c,globals())

#create simple forms for the following models 
names = 'LocationType,LocationPrecision,LocationStatus'
for name in names.split(','):
    create_simple_view(name)



def map_ll(request):
    '''current map view with new map implementation; 
    this new map view uses ajax/ lazy loading to speed up map rendering
    '''
    maplist = [x.plot() for x in get_querysets()]
    args = {'page_name':'map','maplist':maplist}
    return render(request,'locations/map_ll.html',args)


def map_ll_alpha(request):
    '''current map view with new map implementation; 
    this new map view uses ajax/ lazy loading to speed up map rendering
    '''
    d = get_all_location_ids_dict(add_names_gps = True)
    args = {'page_name':'map','d':d}
    return render(request,'locations/map_ll_alpha.html',args)

def map_search(request):
    s = SearchView(request)
    instances = s.search.filter()
    d = get_all_location_ids_dict(instances = instances, add_names_gps = True)
    s.var['page_name']='map search'
    s.var['d']=d
    return render(request, 'locations/map_search.html',s.var)

def simple_map_search(request):
    s = SearchView(request, restrict_to_texts = True)
    instances = s.search.filter()
    d = get_all_location_ids_dict(instances = instances, add_names_gps = True)
    query_terms = query_hints.get_queryterms()
    s.var['page_name']='map search'
    s.var['d']=d
    s.var['query_terms'] = query_terms
    return render(request, 'locations/simple_map_search.html',s.var)

def connection_view(request, text_identifier = None, pk = None):
    Text = apps.get_model('catalogue','Text')
    if text_identifier != None:
        try: pk = text_identifier.split('_')[2]
        except ValueError: print('no pk in text_identifier')
    if pk != None:
        instance = Text.objects.get(pk=pk)
    else: instance = Text.objects.get(pk = 1422)
    # else: raise ValueError('no pk or text_identifier')
    print(instance,'instance')
    f = serializers.serialize('json',[instance])
    print(f,'serial')
    connections = text_connection.text_connection(instance)
    print(connections)
    at = connections.all_texts
    d=get_all_location_ids_dict(instances=at,add_names_gps=True)
    print(d)
    var = {'instances':d,'connection_dict':connections.to_dict(),
        'instance':f}#model_to_dict(instance)}
    return render(request, 'locations/connection_view.html',var)


def map(request):
    '''old style map rendering, all data is prepared beforehand which 
    resulted in slow loading times
    '''
    # maplist = queryset2maplist(get_querysets())
    maplist = None
    args = {'page_name':'map','maplist':maplist}
    return render(request,'locations/map.html',args)

    


def edit_location(request, pk=None, focus = '', view='complete'):
    names='location_relation_formset'
    return edit_model(request, __name__,'Location','locations',pk,
        formset_names=names, 
        focus = focus, view=view)


def mapp(request, location_name = ''):
    if location_name == '': location_name = 'europe'
    map_name = location_name + '.js'
    var = {'map_name':map_name,'location_name':location_name}
    return render(request,'locations/map_location.html',var)


def germany(request):
    location_name = 'germany'
    map_name = location_name + '.js'
    var = {'map_name':map_name,'location_name':location_name}
    return render(request,'locations/markers.html',var)
    

def world(request):
    return render(request,'locations/world.html')

def delete(request, pk, model_name):
    return delete_model(request, __name__,model_name,'locations',pk)
# Create your views here.


def get_querysets(names = None):
    '''load all queryset based on model names in names.
    names can be list or comma seprated string 
    each item should follow this format: app_name$model_name
    '''
    if not names:
        names = 'Text,Illustration,Publication,Publisher,Periodical'.split(',')
        names = ['catalogue$'+name for name in names]
        names.extend('persons$Person,persons$Movement'.split(','))
    if type(names) == str: names = names.spilt(',')
    qs = []
    for name in names:
        app_name,model_name = name.split('$')
        model = apps.get_model(app_name,model_name)
        qs.extend(model.objects.all())
    return qs

def ajax_popup(request,markerid,main_instance_markerid = None):
    '''create a popup based on an async call with the relevant information
    '''
    print(markerid,main_instance_markerid,11111111111)
    app_name, model_name, pk,gps= markerid.split('_')
    latlng = gps2latlng(gps)
    model = apps.get_model(app_name,model_name)
    instance = model.objects.get(pk=pk)
    if main_instance_markerid:
        mi_an, mi_mn, mi_pk,mi_gps= main_instance_markerid.split('_')
        mi_model = apps.get_model(mi_an,mi_mn)
        mi_instance = mi_model.objects.get(pk=mi_pk)
        d = {'popup':instance.pop_up(mi_instance)}
    else:d = {'popup':instance.pop_up(latlng)}
    return JsonResponse(d)

def ajax_links(request,markerid):
    '''show links an instance has with other instance by plotting all on a map.
    '''
    app_name, model_name, pk,gps= markerid.split('_')
    model = apps.get_model(app_name,model_name)
    instance = model.objects.get(pk=pk)
    return JsonResponse({'links':Links(instance).plots})

def ajax_instance(request,app_name,model_name,pk):
    '''returns an instance base on app_name model_name and pk.'''
    model = apps.get_model(app_name,model_name)
    print(model,'model')
    instance = model.objects.get(pk=pk)
    print(instance,'instance')
    f = serializers.serialize('json',[instance])
    print(f,'serial')
    return JsonResponse({'instance':f})

def ajax_instances(request,app_name,model_name,pks):
    '''returns an instance base on app_name model_name and pk.'''
    start = time.time()
    model = apps.get_model(app_name,model_name)
    print('model',time.time() - start)
    print(model,'model')
    pks = pks.split(',')
    instances = model.objects.filter(pk__in = pks)
    print('instances',time.time() - start)
    print(instances,'instances')
    d = [x.sidebar_info for x in instances]
    print('info',time.time() - start)
    #d = serializers.serialize('json',instances)
    # print(d,'serial')
    return JsonResponse({'instances':d})
    

def geojson_file(request,filename):
    '''files used to draw a figure on a map.
    code for source of life map demo
    '''
    if not os.path.isfile('media/geojson/'+filename): data = {'file':False}
    a =  open('media/geojson/'+filename).read()
    try: data = json.loads(a)
    except: data = {'json':False}
    return JsonResponse(data)


def map_draw(request):
    '''view map demo source of life.
    '''
    f = Figure.objects.all()
    f = serializers.serialize('json',f)
    f = json.loads(f)
    s = Style.objects.all()
    s = serializers.serialize('json',s)
    s = json.loads(s)
    args = {'page_name':'map_draw','figures':f,'styles':s}
    return render(request,'locations/map_draw.html',args)

def edit_style(request, pk=None, focus = '', view='complete'):
    '''source of life map demo.
    '''
    return edit_model(request, __name__,'Style','locations',pk, 
        focus = focus, view=view)

def edit_figure(request, pk=None, focus = '', view='complete'):
    '''source of life map demo.
    '''
    return edit_model(request, __name__,'Figure','locations',pk, 
        focus = focus, view=view)

def style_list(request):
    '''source of life map demo
    '''
    return list_view(request, 'Style', 'locations')

def figure_list(request):
    '''source of life map demo
    '''
    return list_view(request, 'Figure', 'locations')
# Create your views here.

locations/templates/locations/OLD/add_geoloc.html
{% extends "utilities/base.html" %}

{% block head %}
	{{form.media.css}}
	<title>{{page_name}}</title>
{% endblock %}


{% block content %}
<form method="post" enctype="multipart/form-data" onsubmit="dosubmit();">
{% csrf_token %}

<div class="col-md-12 d-flex">
<h4 class="mt-2">{{page_name}}</h4>
<a class ="btn btn-link ml-auto" href="{% url 'locations:add_location' %}"
	role="button">location</i></a>
{% if view != "inline" %}
	{% if page_name == "Edit geoloc"%}
	<a class ="btn btn-link ml-auto" href="{% url 'locations:add_geoloc' %}"
	role="button"><i class="fa fa-plus"></i></a>
	{% endif %}
	<a class ="btn btn-link ml-auto" href="{% url 'locations:geoloc_list' %}"
	role="button"><i class="fas fa-list"></i></a>
{% endif %}
</div>


{% include 'utilities/edit_minimize_tab.html' %}

<div class="tab-content">
    <div class="tab-pane fade" id="Edit">
	{%if page_name == "Edit text" and 'unknown' not in crud.last_update %}
		{% include 'utilities/change_log.html' %}
		{% else %} <p class="mb-4"></p>
	{% endif %}
	<!-- text form is defined in a seperate template -->
		<table class="table table-borderless" >
			<tr class="d-flex">
				<th class="col-2">name</th>
				<td class="col-8">{{form.name}} {{form.name.errors}}</td>
			</tr>
			<tr class="d-flex">
				<th class="col-2">location type</th>
				<td class="col-8">{{form.location_type}} {{form.location_type.errors}}</td>
			</tr>
			<tr class="d-flex">
				<th class="col-2">latitude</th>
				<td class="col-8">{{form.latitude}} {{form.latitude.errors}}</td>
			</tr>
			<tr class="d-flex">
				<th class="col-2">longitude</th>
				<td class="col-8">{{form.longitude}} {{form.longitude.errors}}</td>
			</tr>
			<tr class="d-flex">
				<th class="col-2">notes</th>
				<td class="col-8">{{form.notes}} {{form.notes.errors}}</td>
			</tr>
		</table>
    </div>


    <div class="tab-pane fade" id="Minimize">
		<!-- you can minimize the text form -->
		<br>
        <h5 class="mb-1">{{form.instance.title}} </h5> 
		<br>
    </div>
</div>


{% if view == "inline" %}
{% else %}
{% include 'utilities/relation_tabs.html' %}

	<div class="tab-content">

		<div class="tab-pane fade" id="Contained by">
			{{geoloc_relation_formset.management_form}}
			<table class="table table-borderless">
			<tr class ="d-flex">
			<th class="col-8">Location
				<a class = "btn btn-link btn-sm ml-auto" target = "_blank"
					href ="{% url 'locations:add_geoloc' 'inline' %}" role="button">
					 <i class="fa fa-plus"></i></a>
				</th>
			<th><i class="fa fa-times text-danger"></i></th>
			</tr>
			{% for f in geoloc_relation_formset.forms %}
				<tr class ="d-flex">
				<td class="col-8">{{f.container}} {{f.container.errors}}</td>
				<td class="col-1">{{f.DELETE}} {{f.id}}</td>
				</tr>
			{% endfor %}
			</table>
		</div>

	</div>

{% endif %}

<input type="hidden" name="navbar" id="navbar" value="" />
<input type="hidden" name="navcontent" id="navcontent" value="" />
<input type="hidden" name="focus" id="focus" value="" />
<button type="submit" value="Submit" class ="btn btn-success">Save</button>
	{% if view == "inline" %}
		<a type="reset" value="Cancel" class ="btn btn-light"
		href="{% url 'utilities:close' %}">Cancel</a>
	{% else %}
		<button type="submit" name="save" value="add_another"
			 class ="btn btn-outline-success">Save | add another</button>
	{% endif %}
	{% if page_name == "Edit text"%}
    <button type="submit" name="save" value="delete"
		 class ="btn btn-outline-danger">delete</button>
	{% endif %}

{% include 'utilities/tab_selector.html' %}
{{form.media.js}}
{% endblock content %}
 

{% block right %}
{% include 'utilities/complete_approved.html' %}
{% endblock %}

locations/templates/locations/OLD/add_location_old.html
{% extends "utilities/base.html" %}

{% block head %}
	{{form.media.css}}
{% endblock %}

{% block content %}
{% endblock %}
<div class="col-md-12 d-flex">
<h4 class="mt-2">{{page_name}}</h4> 
<a class ="btn btn-link ml-auto" href="{% url 'locations:add_geoloc' %}"
	role="button">add geo location</i></a>
<a class ="btn btn-link ml-auto" href="{% url 'locations:add_userloc' %}"
	role="button">add user location</i></a>
<a class ="btn btn-link ml-auto" href="{% url 'locations:geoloc_list' %}" role="button">geoloc list</a>
<a class ="btn btn-link ml-auto" href="{% url 'locations:location_list' %}" role="button">userloc list</a>
</div>

<p class="text-warning">Please check the help tab</p>


<!-- adding or editing a person -->

{% include 'utilities/location_tabs.html' %}

<div class="tab-content">

    <div class="tab-pane fade" id="Add-from-database">

	<form name="myform" id="myform" method = "post" onsubmit="dosubmit();">
		{% csrf_token %}
	<table class="table table-borderless">
	<tr class ="d-flex">
		<th class="col-2">Location</th>
		<td class="col-8">{{fastform.location}} {{fastform.location.errors}}</td>
	</tr>
	</table>
	<input type="hidden" name="navbar" id="navbar" value="" />
	<input type="hidden" name="navcontent" id="navcontent" value="" />
	<input type="hidden" name="focus" id="focus" value="" />
	<input type="submit" value="Save" class="btn btn-success">
	</form>
	</div>


    <div class="tab-pane fade" id="Help">
	<p>If you want to add a location you can fist check the extended database 
	(with Add-from-database) to see whether you can add it from there.</p>
	<p>If the location is not available in the extended database you can create a new location:</p>
	<ul>
	<li>A real geographic location can be added to the database with 'add geo location'. 
	If a city location is added it is important to add latitude and longitude information
	(can be found on wikipedia or google maps). Once the geolocation is created you
	should use Add-from-database to add it to the available locations.</li>
 	<li>A fictional location or a combination of multiple (geographic) locations 
	 can be added with add user location.</li>
 	<li>You can edit locations by searching them in the geoloc (geolocations) or userloc (user location)
	list and clicking the edit button.
	 </li>
	</ul>
	
	
    </div>
</div>
<hr> 


{% if view == "inline" %}
	<a type="reset" value="Cancel" class ="btn btn-light"
	href="{% url 'utilities:close' %}">Cancel</a>
{% endif %}


{{form.media.js}}

{% include 'utilities/tab_selector.html' %}



 

locations/templates/locations/OLD/add_userloc.html
{% extends "utilities/base.html" %}

{% block head %}
	{{form.media.css}}
	<title>{{page_name}}</title>
{% endblock %}


{% block content %}
<form method="post" enctype="multipart/form-data" onsubmit="dosubmit();">
{% csrf_token %}

<div class="col-md-12 d-flex">
<h4 class="mt-2">{{page_name}}</h4>
<a class ="btn btn-link ml-auto" href="{% url 'locations:add_location' %}"
	role="button">location</i></a>
{% if view != "inline" %}
	{% if page_name == "Edit geoloc"%}
	<a class ="btn btn-link ml-auto" href="{% url 'locations:add_userloc' %}"
	role="button"><i class="fa fa-plus"></i></a>
	{% endif %}
	<a class ="btn btn-link ml-auto" href="{% url 'locations:location_list' %}"
	role="button"><i class="fas fa-list"></i></a>
{% endif %}
</div>


{% include 'utilities/edit_minimize_tab.html' %}

<div class="tab-content">
    <div class="tab-pane fade" id="Edit">
	{%if page_name == "Edit text" and 'unknown' not in crud.last_update %}
		{% include 'utilities/change_log.html' %}
		{% else %} <p class="mb-4"></p>
	{% endif %}
	<!-- text form is defined in a seperate template -->
		<table class="table table-borderless" >
			<tr class="d-flex">
				<th class="col-2">name</th>
				<td class="col-8">{{form.name}} {{form.name.errors}}</td>
			</tr>
			<tr class="d-flex">
				<th class="col-2">locations</th>
				<td class="col-8">{{form.geolocs}} {{form.geolocs.errors}}</td>
			</tr>
			<tr class="d-flex">
				<th class="col-2">type</th>
				<td class="col-8">{{form.loc_type}} {{form.loc_type.errors}}</td>
			</tr>
			<tr class="d-flex">
				<th class="col-2">status</th>
				<td class="col-8">{{form.status}} {{form.status.errors}}</td>
			
			</tr>
			<tr class="d-flex">
				<th class="col-2">precision</th>
				<td class="col-8">{{form.loc_precision}} 
					{{form.loc_precision.errors}}</td>
			</tr>
			<tr class="d-flex">
				<th class="col-2">notes</th>
				<td class="col-8">{{form.notes}} {{form.notes.errors}}</td>
			</tr>
		</table>
    </div>


    <div class="tab-pane fade" id="Minimize">
		<!-- you can minimize the text form -->
		<br>
        <h5 class="mb-1">{{form.instance.title}} </h5> 
		<br>
    </div>
</div>



<input type="hidden" name="navbar" id="navbar" value="" />
<input type="hidden" name="navcontent" id="navcontent" value="" />
<input type="hidden" name="focus" id="focus" value="" />
<button type="submit" value="Submit" class ="btn btn-success">Save</button>
	{% if view == "inline" %}
		<a type="reset" value="Cancel" class ="btn btn-light"
		href="{% url 'utilities:close' %}">Cancel</a>
	{% else %}
		<button type="submit" name="save" value="add_another"
			 class ="btn btn-outline-success">Save | add another</button>
	{% endif %}
	{% if page_name == "Edit text"%}
    <button type="submit" name="save" value="delete"
		 class ="btn btn-outline-danger">delete</button>
	{% endif %}

{% include 'utilities/tab_selector.html' %}
{{form.media.js}}
{% endblock content %}
 

{% block right %}
{% include 'utilities/complete_approved.html' %}
{% endblock %}

locations/templates/locations/OLD/geoloc_list.html
<!-- test view to print data in a table from model --> 
{% extends "utilities/base.html" %}

{% block head %}
	<title>{{page_name}}</title>
{% endblock %}

{% block content %}
{% include 'utilities/list_search_bar.html' %}
{% if geoloc_list %}

<div class="d-flex">
<table class="table table-hover">
	<tr> 
	<th><a href="?order_by=name,{{order}},{{direction}},{{query}}" 
		style="text-decoration:none;">Name</a></th>
	<th class="text-primary">Country</th>
	<th class="text-primary">Region</th>
	<th></th>
	</tr>
	{% for location in geoloc_list %}
		<td>{{location.name}}</td>
		<td>{{location.country}}</td>
		<td>{{location.region}}</td>
		<td style="white-space:nowrap;"><a class = "btn btn-link btn-sm ml-auto"
        href ="{% url 'locations:delete' location.pk 'GeoLoc' %}"
        role="button"><i class="fa fa-trash text-secondary"></i></a>
		<a class = "btn btn-link btn-sm ml-auto"
        href ="{% url 'locations:edit_geoloc' location.pk %}"
        role="button"><i class="far fa-edit text-secondary"></i></a></td>
	</tr>
	{% endfor %}
</table>

<a class ="btn btn-link ml-auto" href="{% url 'locations:add_geoloc' %}" 
role="button">Add geo location</a>
</div>


{% else %}
	<p>no locations are available</p>
{% endif %}
{% endblock content %}